spring.application.name=kosmo163_boot

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#데이터 정보 
spring.datasource.hikari.username=cns
spring.datasource.hikari.password=cns
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#mybatis의 정보
#스네이크 케이스를 카멜케이스로 바꾸는것
mybatis.configuration.map-underscore-to-camel-case=true

# config의 typealias를 대체한다. 
# 같은 클래스 명이 존재하면 에러 발생
mybatis.type-aliases-package=com.naver.sth

#file 관리를 위한 설정 
# multipart 사용여부
spring.servlet.multipart.enabled=true

#file 하나당 최대 크기 설정 제한
spring.servlet.multipart.max-file-size=10MB

# 총 file의 최대 크기 설정제한
spring.servlet.multipart.max-request-size=100MB


# 파일 저장 관리
app.upload.base=C:\\upload\\
